# appspec.yml
version: 0.0
Resources:
  - TravelFixLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: TravelFixLambdaFunction
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2

Hooks:
  BeforeAllowTraffic:
    - LambdaFunctionToInvoke: LambdaValidationFunctionBeforeTrafficShift
      Timeout: 180
  AfterAllowTraffic:
    - LambdaFunctionToInvoke: LambdaValidationFunctionAfterTrafficShift
      Timeout: 180
