version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Packaging the Lambda function...
      - zip -r TravelFixLambdaFunction.zip .
  post_build:
    commands:
      - echo Uploading the packaged Lambda function to S3...
      - aws s3 cp TravelFixLambdaFunction.zip s3://travel-fix-lambda-deployment/TravelFixCodePipelin/BuildArtif/ --region us-east-1

artifacts:
  files:
    - TravelFixLambdaFunction.zip
  discard-paths: yes
