version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Packaging the Lambda function...
      - zip -r TravelFixLambdaFunction.zip . -x appspec.yml   # Exclude appspec.yml
  post_build:
    commands:
      - echo Uploading the packaged Lambda function to S3...
      - aws s3 cp TravelFixLambdaFunction.zip s3://travel-fix-lambda-deployment/TravelFixLambdaCodeP/BuildArtif/ --region us-east-1
      - aws s3 cp appspec.yml s3://travel-fix-lambda-deployment/TravelFixLambdaCodeP/BuildArtif/ --region us-east-1  # Upload appspec.yml separately

artifacts:
  files:
    - TravelFixLambdaFunction.zip
  discard-paths: yes
